/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClaimRouteImport } from './routes/_authenticated/claim'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedMatchupsRouteImport } from './routes/_authenticated/matchups'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRivalriesRouteImport } from './routes/_authenticated/rivalries'
import { Route as AuthenticatedRostersRouteImport } from './routes/_authenticated/rosters'
import { Route as AuthenticatedManagersIndexRouteImport } from './routes/_authenticated/managers.index'
import { Route as AuthenticatedManagersKeyRouteImport } from './routes/_authenticated/managers.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimRoute = AuthenticatedClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchupsRoute = AuthenticatedMatchupsRouteImport.update({
  id: '/matchups',
  path: '/matchups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRivalriesRoute = AuthenticatedRivalriesRouteImport.update({
  id: '/rivalries',
  path: '/rivalries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRostersRoute = AuthenticatedRostersRouteImport.update({
  id: '/rosters',
  path: '/rosters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagersIndexRoute =
  AuthenticatedManagersIndexRouteImport.update({
    id: '/managers/',
    path: '/managers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagersKeyRoute =
  AuthenticatedManagersKeyRouteImport.update({
    id: '/managers/$key',
    path: '/managers/$key',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/claim': typeof AuthenticatedClaimRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/matchups': typeof AuthenticatedMatchupsRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rivalries': typeof AuthenticatedRivalriesRoute
  '/rosters': typeof AuthenticatedRostersRoute
  '/managers/$key': typeof AuthenticatedManagersKeyRoute
  '/managers/': typeof AuthenticatedManagersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/claim': typeof AuthenticatedClaimRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/matchups': typeof AuthenticatedMatchupsRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rivalries': typeof AuthenticatedRivalriesRoute
  '/rosters': typeof AuthenticatedRostersRoute
  '/managers/$key': typeof AuthenticatedManagersKeyRoute
  '/managers': typeof AuthenticatedManagersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/claim': typeof AuthenticatedClaimRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/matchups': typeof AuthenticatedMatchupsRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rivalries': typeof AuthenticatedRivalriesRoute
  '/_authenticated/rosters': typeof AuthenticatedRostersRoute
  '/_authenticated/managers/$key': typeof AuthenticatedManagersKeyRoute
  '/_authenticated/managers/': typeof AuthenticatedManagersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/claim'
    | '/drafts'
    | '/matchups'
    | '/players'
    | '/profile'
    | '/rivalries'
    | '/rosters'
    | '/managers/$key'
    | '/managers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/claim'
    | '/drafts'
    | '/matchups'
    | '/players'
    | '/profile'
    | '/rivalries'
    | '/rosters'
    | '/managers/$key'
    | '/managers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/claim'
    | '/_authenticated/drafts'
    | '/_authenticated/matchups'
    | '/_authenticated/players'
    | '/_authenticated/profile'
    | '/_authenticated/rivalries'
    | '/_authenticated/rosters'
    | '/_authenticated/managers/$key'
    | '/_authenticated/managers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claim': {
      id: '/_authenticated/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof AuthenticatedClaimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchups': {
      id: '/_authenticated/matchups'
      path: '/matchups'
      fullPath: '/matchups'
      preLoaderRoute: typeof AuthenticatedMatchupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rivalries': {
      id: '/_authenticated/rivalries'
      path: '/rivalries'
      fullPath: '/rivalries'
      preLoaderRoute: typeof AuthenticatedRivalriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rosters': {
      id: '/_authenticated/rosters'
      path: '/rosters'
      fullPath: '/rosters'
      preLoaderRoute: typeof AuthenticatedRostersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/managers/': {
      id: '/_authenticated/managers/'
      path: '/managers'
      fullPath: '/managers/'
      preLoaderRoute: typeof AuthenticatedManagersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/managers/$key': {
      id: '/_authenticated/managers/$key'
      path: '/managers/$key'
      fullPath: '/managers/$key'
      preLoaderRoute: typeof AuthenticatedManagersKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClaimRoute: typeof AuthenticatedClaimRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedMatchupsRoute: typeof AuthenticatedMatchupsRoute
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRivalriesRoute: typeof AuthenticatedRivalriesRoute
  AuthenticatedRostersRoute: typeof AuthenticatedRostersRoute
  AuthenticatedManagersKeyRoute: typeof AuthenticatedManagersKeyRoute
  AuthenticatedManagersIndexRoute: typeof AuthenticatedManagersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClaimRoute: AuthenticatedClaimRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedMatchupsRoute: AuthenticatedMatchupsRoute,
  AuthenticatedPlayersRoute: AuthenticatedPlayersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRivalriesRoute: AuthenticatedRivalriesRoute,
  AuthenticatedRostersRoute: AuthenticatedRostersRoute,
  AuthenticatedManagersKeyRoute: AuthenticatedManagersKeyRoute,
  AuthenticatedManagersIndexRoute: AuthenticatedManagersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
